# Generated by Django 4.2.6 on 2023-10-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.TextField()),
                ('artist', models.TextField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
