# Generated by Django 4.2.6 on 2023-10-19 19:25

from django.db import migrations

def load_initial_data(apps, schema_editor):
    cd_model = apps.get_model('api_app', 'CD')
    cd_model.objects.create (album = "I Put a Spell On You", artist = "Nina Simone", year = 1965)
    cd_model.objects.create (album = "Dock of the Bay", artist = "Otis Redding", year = 1968)
    cd_model.objects.create (album = "All Things Must Pass", artist = "George Harrison", year = 1970)
    cd_model.objects.create (album = "Bridge Over Troubled Water", artist = "Simon and Garfunkel", year = 1970)
    cd_model.objects.create (album = "9 to 5 and Odd Jobs", artist = "Dolly Parton", year = 1980)
    cd_model.objects.create (album = "Voices", artist = "Daryl Hall & John Oates", year = 1980)
    cd_model.objects.create (album = "Purple Rain", artist = "Prince", year = 1984)
    cd_model.objects.create (album = "Tapestry", artist = "Carole King", year = 1971)
    cd_model.objects.create (album = "Songs in the Key of Life", artist = "Stevie Wonder", year = 1976)
    cd_model.objects.create (album = "Where Did Our Love Go", artist = "The Supremes", year = 1964)

class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
